version: '3'

volumes:
  booking_member_maria:
    external:
      name: booking_member_maria

networks:
  booking_member_service_network: # 이 섹션은 외부 네트워크에 연결을 정의합니다.
    driver: bridge


services:
  booking_member_maria:
    restart: on-failure
    image: 'mariadb:10.3'
    container_name: 'member-db-container'
    environment:
      MYSQL_DATABASE: booking_member
      MYSQL_USER: booking  
      MYSQL_PASSWORD: booking123!
      MYSQL_ROOT_PASSWORD: booking123!
      TZ: Asia/Seoul
    networks:
      - booking_member_service_network
    volumes:
      - 'booking_member_maria:/var/lib/mysql'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    expose:
    - "3306"

  booking_member_server:
    restart: on-failure
    depends_on:
      - booking_member_maria
    image: 'member-image:latest'
    container_name: 'member-container'
    environment:
      CONFIG_URL: 'http://172.26.14.101:8123'
      # SPRING_DATASOURCE_URL: 'jdbc:mariadb://booking_member_maria:3306/booking_member'
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: booking123!

    ports:
      - '9001:9001'
    networks:
      - booking_member_service_network
